### ISSUE TITLE
Provide the schema(crawler) diagram of the database on the README

### ISSUE THREAD

**Issue by adriens** [schemacrawler/chinook-database#29]
# Idea

To better understand how this database looks like and schemacrawler features:

- Provide the SC command line that can be used to generate the diagram (the Docker way would be cool)
- Put the outuput image in the README (acts as a teaser for SC)

**Comment by sualeh** [comment]
Done! Using the brand new SchemaCrawler Action for GitHub Actions.

**Comment by adriens** [comment]
> new SchemaCrawler Action for GitHub Actions.

😎

**Comment by adriens** [comment]
Yesss 
![image](https://user-images.githubusercontent.com/5235127/97412100-32cad400-1955-11eb-87ba-63636455ca98.png)

Can't wait to see what the mermaid js version will look like

**Comment by sualeh** [comment]
@adriens - MermaidJS is still not ready with a detailed diagram like this one.

**Comment by adriens** [comment]
Sure, sure !
